DATA SEGMENT
    PORTA EQU 280H
    PORTB EQU 281H
    PORTC EQU 282H
    PORTR EQU 283H
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV DX,PORTR
    MOV AL,90H
    OUT DX,AL
    MOV AL,01H
    MOV AH,AL
TEST1:
    MOV DX,PORTA
    IN AL,DX
    CMP AL,00000001B
    JNZ TEST1
    MOV AL,AH
    MOV DX,PORTC
    OUT DX,AL
    ROL AL,1
    MOV BX,100H
DELAY:
    MOV CX,0FFFFH
LOOP1:
    LOOP LOOP1
    DEC BX
    JNZ DELAY
    MOV AH,AL
    JMP TEST1
CODE ENDS
END START